name: Deploy on Dev Push

on:
  push:
    branches:
      - dev  # 仅在 dev 分支有新提交时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # 根据项目需求指定 Node.js 版本

      # 3. 安装依赖
      - name: Install dependencies
        run: npm install

      # 4. 赋予 deploy_script.bash 执行权限
      - name: Make deploy_script.bash executable
        run: chmod +x ./deploy_script.bash

      # 5. 运行部署脚本
      - name: Run deploy script
        run: npm run deploy
