name: Deploy and Update Log on Dev Push

on:
  push:
    branches:
      - dev  # 仅在 dev 分支有新提交时触发

jobs:
  deploy-and-update-log:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码（默认检出 dev 分支）
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整的提交历史

      # 2. 获取 dev 分支上最新的提交信息
      - name: Get latest commit info from dev branch
        id: commit
        run: |
          echo "::set-output name=date::$(git log -1 --format=%cd --date=short)"
          echo "::set-output name=author::$(git log -1 --format=%an)"
          echo "::set-output name=message::$(git log -1 --format=%s)"

      # 3. 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # 根据项目需求指定 Node.js 版本

      # 4. 安装依赖
      - name: Install dependencies
        run: npm install

      # 5. 打包项目
      - name: Build project
        run: npm run build

      # 6. 检查是否成功生成 dist 目录
      - name: Check dist directory
        run: |
          if [ ! -d "dist" ]; then
            echo "Error: dist directory not found. Build failed."
            exit 1
          fi

      # 7. 生成唯一的临时分支名称
      - name: Generate temporary branch name
        id: temp-branch
        run: |
          TEMP_BRANCH="temp-deploy-$(date +%s)"
          echo "temp_branch=$TEMP_BRANCH" >> $GITHUB_OUTPUT

      # 8. 拉取 main 分支的提交历史
      - name: Fetch main branch
        run: |
          git fetch origin main:main

      # 9. 检查临时分支是否存在，如果存在则删除
      - name: Delete existing temporary branch
        run: |
          if git show-ref --quiet refs/heads/"${{ steps.temp-branch.outputs.temp_branch }}"; then
            echo "Deleting existing temporary branch..."
            git branch -D "${{ steps.temp-branch.outputs.temp_branch }}"
          fi

      # 10. 基于 main 分支创建临时分支
      - name: Create temporary branch
        run: |
          git checkout -b "${{ steps.temp-branch.outputs.temp_branch }}" main

      # 11. 清空当前目录（除了 .git、dist、node_modules 和 articles 目录）
      - name: Clean current directory
        run: |
          find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name 'dist' ! -name 'node_modules' ! -name 'articles' -exec rm -rf {} +

      # 12. 创建 .gitignore 文件，屏蔽 node_modules 和 dist 等目录
      - name: Create .gitignore file
        run: |
          cat <<EOL > .gitignore
          # Ignore node_modules and dist directories
          node_modules/
          dist/

          # Ignore other build artifacts
          *.log
          *.tmp
          .DS_Store
          EOL

      # 13. 将 dist 目录中的内容复制到当前目录
      - name: Copy dist contents
        run: |
          cp -r dist/* .

      # 14. 创建 articles 文件夹（如果不存在）
      - name: Create articles directory
        run: mkdir -p articles

      # 15. 更新 log.md 文件（追加新记录）
      - name: Update log.md
        run: |
          LOG_FILE="articles/log.md"
          if [ ! -f "$LOG_FILE" ]; then
            echo "# Commit Log" > "$LOG_FILE"
            echo "" >> "$LOG_FILE"
          fi
          echo "## ${{ steps.commit.outputs.date }}" >> "$LOG_FILE"
          echo "- **Author**: ${{ steps.commit.outputs.author }}" >> "$LOG_FILE"
          echo "- **Message**: ${{ steps.commit.outputs.message }}" >> "$LOG_FILE"
          echo "" >> "$LOG_FILE"

      # 16. 配置 Git 用户信息
      - name: Configure Git user information
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # 17. 提交更改
      - name: Commit changes
        run: |
          git add .
          if ! git commit -m "Deploy: Update main branch with latest build and log.md"; then
            echo "Error: Failed to commit changes."
            exit 1
          fi

      # 18. 推送临时分支并创建 Pull Request
      - name: Push temporary branch and create PR
        run: |
          git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin "${{ steps.temp-branch.outputs.temp_branch }}"
          gh pr create --base main --head "${{ steps.temp-branch.outputs.temp_branch }}" --title "Deploy: Update main branch with latest build and log.md" --body "Automated deployment of the latest build and update of log.md."
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # 19. 等待 PR 创建完成
      - name: Wait for PR creation
        run: sleep 10  # 等待 10 秒，确保 PR 已创建

      # 20. 自动合并 Pull Request
      - name: Merge Pull Request
        run: |
          gh pr merge "${{ steps.temp-branch.outputs.temp_branch }}" --merge --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # 21. 切换回 dev 分支
      - name: Switch back to dev branch
        run: |
          git checkout dev

      # 22. 完成部署和日志更新
      - name: Complete deployment and log update
        run: |
          echo "Deployment to origin/main and log.md update completed successfully!"
