name: Update Log on Dev Push

on:
  push:
    branches:
      - dev  # 仅在 dev 分支有新提交时触发

jobs:
  update-log:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整的提交历史

      # 2. 拉取远程 main 分支并创建临时分支
      - name: Fetch main branch and create temporary branch
        run: |
          git fetch origin main:main  # 拉取远程 main 分支到本地
          git checkout -b temp-log-update main  # 基于 main 分支创建临时分支

      # 3. 创建 articles 文件夹（如果不存在）
      - name: Create articles directory
        run: mkdir -p articles

      # 4. 获取最新提交信息
      - name: Get latest commit info
        id: commit
        run: |
          echo "::set-output name=date::$(git log -1 --format=%cd --date=short)"
          echo "::set-output name=author::$(git log -1 --format=%an)"
          echo "::set-output name=message::$(git log -1 --format=%s)"

      # 5. 创建或更新 log.md 文件
      - name: Update log.md
        run: |
          LOG_FILE="articles/log.md"
          if [ ! -f "$LOG_FILE" ]; then
            echo "# Commit Log" > "$LOG_FILE"
            echo "" >> "$LOG_FILE"
          fi
          echo "## $(git log -1 --format=%cd --date=short)" >> "$LOG_FILE"
          echo "- **Author**: $(git log -1 --format=%an)" >> "$LOG_FILE"
          echo "- **Message**: $(git log -1 --format=%s)" >> "$LOG_FILE"
          echo "" >> "$LOG_FILE"

      # 6. 提交更改到临时分支
      - name: Commit changes to temporary branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add articles/log.md
          git commit -m "Update log.md with latest commit info"

      # 7. 推送临时分支并创建 Pull Request
      - name: Push temporary branch and create PR
        run: |
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git push origin temp-log-update
          gh pr create --base main --head temp-log-update --title "Update log.md" --body "Automated update of log.md file."
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
